"""Add quran memorisation

Revision ID: 0a09bada6746
Revises: adf54d6bcf42
Create Date: 2026-08-01 10:55:42.546444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a09bada6746'
down_revision: Union[str, Sequence[str], None] = 'adf54d6bcf42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quran_memorisation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_memorisation_user_id'), 'quran_memorisation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quran_memorisation_user_id'), table_name='quran_memorisation')
    op.drop_table('quran_memorisation')
    # ### end Alembic commands ###
