"""Add GenericHabitORM and HabitCompletionORM for Phase 5A

Revision ID: 2c2782b473f8
Revises: 9ebdd8f2741f
Create Date: 2026-08-03 13:58:37.933409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2782b473f8'
down_revision: Union[str, Sequence[str], None] = '9ebdd8f2741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habit_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('habit_id', sa.String(length=36), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_completions_completed_date'), 'habit_completions', ['completed_date'], unique=False)
    op.create_index(op.f('ix_habit_completions_habit_id'), 'habit_completions', ['habit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_completions_habit_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_completed_date'), table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
