"""add_fasting_logs

Revision ID: 5a331927dd77
Revises: 92bd8337956e
Create Date: 2026-07-31 14:56:14.598555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a331927dd77'
down_revision: Union[str, Sequence[str], None] = '92bd8337956e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fasting_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasting_logs_date'), 'fasting_logs', ['date'], unique=False)
    op.create_index(op.f('ix_fasting_logs_user_id'), 'fasting_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fasting_logs_user_id'), table_name='fasting_logs')
    op.drop_index(op.f('ix_fasting_logs_date'), table_name='fasting_logs')
    op.drop_table('fasting_logs')
    # ### end Alembic commands ###
