"""initial_schema

Revision ID: 92bd8337956e
Revises: 7fc26f71edb0
Create Date: 2026-07-31 14:52:59.825984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bd8337956e'
down_revision: Union[str, Sequence[str], None] = '7fc26f71edb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('family_invitations_hashed_token_key'), 'family_invitations', type_='unique')
    op.drop_column('family_invitations', 'hashed_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_invitations', sa.Column('hashed_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('family_invitations_hashed_token_key'), 'family_invitations', ['hashed_token'])
    # ### end Alembic commands ###
