"""Add prayer journal

Revision ID: adf54d6bcf42
Revises: b2c3d4e5f6a7
Create Date: 2026-08-01 10:54:16.072565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf54d6bcf42'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer_journals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prayer_name', sa.String(length=16), nullable=False),
    sa.Column('khushoo_rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('distractions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_journals_date'), 'prayer_journals', ['date'], unique=False)
    op.create_index(op.f('ix_prayer_journals_user_id'), 'prayer_journals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prayer_journals_user_id'), table_name='prayer_journals')
    op.drop_index(op.f('ix_prayer_journals_date'), table_name='prayer_journals')
    op.drop_table('prayer_journals')
    # ### end Alembic commands ###
