"""Add phase 4A models: planner_days, planner_time_blocks

Revision ID: c17fc1433675
Revises: ed44aef6c360
Create Date: 2026-08-03 12:41:06.787643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17fc1433675'
down_revision: Union[str, Sequence[str], None] = 'ed44aef6c360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_days_date'), 'planner_days', ['date'], unique=False)
    op.create_index(op.f('ix_planner_days_user_id'), 'planner_days', ['user_id'], unique=False)
    op.create_table('planner_time_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['planner_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_time_blocks_day_id'), 'planner_time_blocks', ['day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planner_time_blocks_day_id'), table_name='planner_time_blocks')
    op.drop_table('planner_time_blocks')
    op.drop_index(op.f('ix_planner_days_user_id'), table_name='planner_days')
    op.drop_index(op.f('ix_planner_days_date'), table_name='planner_days')
    op.drop_table('planner_days')
    # ### end Alembic commands ###
