"""Add phase 3 models: dua_bookmarks, learning

Revision ID: ed44aef6c360
Revises: 0a09bada6746
Create Date: 2026-08-03 12:34:41.265615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed44aef6c360'
down_revision: Union[str, Sequence[str], None] = '0a09bada6746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dua_bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dua_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dua_bookmarks_dua_id'), 'dua_bookmarks', ['dua_id'], unique=False)
    op.create_index(op.f('ix_dua_bookmarks_user_id'), 'dua_bookmarks', ['user_id'], unique=False)
    op.create_table('learning_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('completed_modules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_enrollments_path_id'), 'learning_enrollments', ['path_id'], unique=False)
    op.create_index(op.f('ix_learning_enrollments_user_id'), 'learning_enrollments', ['user_id'], unique=False)
    op.create_table('learning_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_modules_path_id'), 'learning_modules', ['path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_modules_path_id'), table_name='learning_modules')
    op.drop_table('learning_modules')
    op.drop_index(op.f('ix_learning_enrollments_user_id'), table_name='learning_enrollments')
    op.drop_index(op.f('ix_learning_enrollments_path_id'), table_name='learning_enrollments')
    op.drop_table('learning_enrollments')
    op.drop_index(op.f('ix_dua_bookmarks_user_id'), table_name='dua_bookmarks')
    op.drop_index(op.f('ix_dua_bookmarks_dua_id'), table_name='dua_bookmarks')
    op.drop_table('dua_bookmarks')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
