/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedDhikrRouteImport } from './routes/_authenticated/dhikr'
import { Route as AuthenticatedDuasRouteImport } from './routes/_authenticated/duas'
import { Route as AuthenticatedFamiliesRouteImport } from './routes/_authenticated/families'
import { Route as AuthenticatedHadithRouteImport } from './routes/_authenticated/hadith'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPrayerJournalRouteImport } from './routes/_authenticated/prayer-journal'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuranRouteImport } from './routes/_authenticated/quran'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDhikrRoute = AuthenticatedDhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuasRoute = AuthenticatedDuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliesRoute = AuthenticatedFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHadithRoute = AuthenticatedHadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerJournalRoute =
  AuthenticatedPrayerJournalRouteImport.update({
    id: '/prayer-journal',
    path: '/prayer-journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuranRoute = AuthenticatedQuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dhikr': typeof AuthenticatedDhikrRoute
  '/duas': typeof AuthenticatedDuasRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/hadith': typeof AuthenticatedHadithRoute
  '/home': typeof AuthenticatedHomeRoute
  '/prayer-journal': typeof AuthenticatedPrayerJournalRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dhikr': typeof AuthenticatedDhikrRoute
  '/duas': typeof AuthenticatedDuasRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/hadith': typeof AuthenticatedHadithRoute
  '/home': typeof AuthenticatedHomeRoute
  '/prayer-journal': typeof AuthenticatedPrayerJournalRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dhikr': typeof AuthenticatedDhikrRoute
  '/_authenticated/duas': typeof AuthenticatedDuasRoute
  '/_authenticated/families': typeof AuthenticatedFamiliesRoute
  '/_authenticated/hadith': typeof AuthenticatedHadithRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/prayer-journal': typeof AuthenticatedPrayerJournalRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quran': typeof AuthenticatedQuranRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/assistant'
    | '/dhikr'
    | '/duas'
    | '/families'
    | '/hadith'
    | '/home'
    | '/prayer-journal'
    | '/profile'
    | '/quran'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/assistant'
    | '/dhikr'
    | '/duas'
    | '/families'
    | '/hadith'
    | '/home'
    | '/prayer-journal'
    | '/profile'
    | '/quran'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_authenticated/assistant'
    | '/_authenticated/dhikr'
    | '/_authenticated/duas'
    | '/_authenticated/families'
    | '/_authenticated/hadith'
    | '/_authenticated/home'
    | '/_authenticated/prayer-journal'
    | '/_authenticated/profile'
    | '/_authenticated/quran'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dhikr': {
      id: '/_authenticated/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof AuthenticatedDhikrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duas': {
      id: '/_authenticated/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof AuthenticatedDuasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families': {
      id: '/_authenticated/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AuthenticatedFamiliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hadith': {
      id: '/_authenticated/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof AuthenticatedHadithRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer-journal': {
      id: '/_authenticated/prayer-journal'
      path: '/prayer-journal'
      fullPath: '/prayer-journal'
      preLoaderRoute: typeof AuthenticatedPrayerJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quran': {
      id: '/_authenticated/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof AuthenticatedQuranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDhikrRoute: typeof AuthenticatedDhikrRoute
  AuthenticatedDuasRoute: typeof AuthenticatedDuasRoute
  AuthenticatedFamiliesRoute: typeof AuthenticatedFamiliesRoute
  AuthenticatedHadithRoute: typeof AuthenticatedHadithRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPrayerJournalRoute: typeof AuthenticatedPrayerJournalRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuranRoute: typeof AuthenticatedQuranRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDhikrRoute: AuthenticatedDhikrRoute,
  AuthenticatedDuasRoute: AuthenticatedDuasRoute,
  AuthenticatedFamiliesRoute: AuthenticatedFamiliesRoute,
  AuthenticatedHadithRoute: AuthenticatedHadithRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPrayerJournalRoute: AuthenticatedPrayerJournalRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuranRoute: AuthenticatedQuranRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
